# Generated by Django 2.2.13 on 2020-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('job_location', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50, null=True)),
                ('technical_skillset', models.CharField(max_length=400, null=True)),
                ('work_experience', models.CharField(max_length=20, null=True)),
                ('employment_authorization', models.CharField(max_length=10, null=True)),
                ('loginid', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('registration', models.CharField(default='No', max_length=3)),
            ],
        ),
    ]
