# Generated by Django 2.2.13 on 2020-12-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20201122_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=50, null=True)),
                ('date_time_scrapped', models.CharField(max_length=50, null=True)),
                ('searched_job_title', models.CharField(max_length=100, null=True)),
                ('searched_job_location', models.CharField(max_length=100, null=True)),
                ('job_portal', models.CharField(max_length=50, null=True)),
                ('job_date_posted', models.CharField(max_length=100, null=True)),
                ('job_title', models.CharField(max_length=400, null=True)),
                ('job_company_name', models.CharField(max_length=400, null=True)),
                ('job_location', models.CharField(max_length=400, null=True)),
                ('job_phone_no', models.CharField(max_length=100, null=True)),
                ('job_email', models.CharField(max_length=200, null=True)),
                ('job_link', models.CharField(max_length=2000, null=True)),
                ('job_description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
