# Generated by Django 2.2.13 on 2020-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20201218_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email_active_field',
            field=models.BooleanField(default=False),
        ),
    ]
